const lang = {
    en: {
      search: "Search",
      gptSearchPlaceholder: "What would you like to watch today?",
      SEARCH_MOVIE_BY_NAME:"Search Movie By Name",
      SEARCH_MOVIE:"Search Movie",
      RESET:"Reset",
      HOMEPAGE:"Homepage",
      GPT_SEARCH:"GPT Search",
      PLAY:"Play",
      MORE_INFO:"More Info",
      NOW_PLAYING:"Now Playing",
      TRANDING:"Trending",
      POPULAR:"Popular",
      UPCOM_MOVI:"Upcoming Movies",
      HORROR:"Horror",
      COMEDY:"Comedy",
    },
    hindi: {
      search: "खोज",
      gptSearchPlaceholder: "आज आप क्या देखना चाहेंगे?",
      SEARCH_MOVIE_BY_NAME:"नाम से मूवी खोजें",
      SEARCH_MOVIE:"मूवी खोजें",
      RESET:"रीसेट",
      HOMEPAGE:"मुखपृष्ठ",
      GPT_SEARCH:"जीपीटी खोज",
      PLAY:"खेल",
      MORE_INFO:"और जानकारी",
      NOW_PLAYING:"अब खेल रहे हैं",
      TRANDING:"ट्रेंडिंग",
      POPULAR:"लोकप्रिय",
      UPCOM_MOVI:"आगामी फिल्में",
      HORROR:"डरावनी",
      COMEDY:"कॉमेडी",
    },
    spanish: {
      search: "buscar",
      gptSearchPlaceholder: "¿Qué te gustaría ver hoy?",
      SEARCH_MOVIE_BY_NAME:"Buscar película por nombre",
      SEARCH_MOVIE:"Buscar película",
      RESET:"Reiniciar",
      HOMEPAGE:"Página principal",
      GPT_SEARCH:"Búsqueda GPT",
      PLAY:"Jugar",
      MORE_INFO:"Más información",
      NOW_PLAYING:"Jugando ahora",
      TRANDING:"Tendencias",
      POPULAR:"Popular",
      UPCOM_MOVI:"Próximas películas",
      HORROR:"Horror",
      COMEDY:"Comedia",
    },
  };
  
  export default lang;
  